define images = [
    ZNGalleryImage("bg club.jpg", seenImage="bg club", fullsize="bg club.jpg"),
    ZNGalleryImage("bg meadow.jpg", seenImage="bg meadow", fullsize="bg meadow.jpg"),
    ZNGalleryImage("bg uni.jpg", seenImage="bg uni", fullsize="bg uni.jpg"),
    ZNGalleryImage("bg meadow.jpg", seenImage="bg meadow", fullsize="bg meadow.jpg"),
    ZNGalleryImage("bg uni.jpg", seenImage="bg uni", fullsize="bg uni.jpg"),
    ZNGalleryImage("bg club.jpg", seenImage="bg club", fullsize="bg club.jpg"),
    ZNGalleryImage("bg club.jpg", seenImage="bg club", fullsize="bg club.jpg"),
    ZNGalleryImage("bg meadow.jpg", seenImage="bg meadow", fullsize="bg meadow.jpg"),
    ZNGalleryImage("bg uni.jpg", seenImage="bg uni", fullsize="bg uni.jpg"),
    ZNGalleryImage("bg meadow.jpg", seenImage="bg meadow", fullsize="bg meadow.jpg"),
    ZNGalleryImage("bg uni.jpg", seenImage="bg uni", fullsize="bg uni.jpg"),
    ZNGalleryImage("bg club.jpg", seenImage="bg club", fullsize="bg club.jpg"),
    ZNGalleryImage("bg club.jpg", seenImage="bg club", fullsize="bg club.jpg"),
    ZNGalleryImage("bg meadow.jpg", seenImage="bg meadow", fullsize="bg meadow.jpg"),
    ZNGalleryImage("bg uni.jpg", seenImage="bg uni", fullsize="bg uni.jpg"),
    ZNGalleryImage("bg meadow.jpg", seenImage="bg meadow", fullsize="bg meadow.jpg"),
    ZNGalleryImage("bg uni.jpg", seenImage="bg uni", fullsize="bg uni.jpg"),
    ZNGalleryImage("bg club.jpg", seenImage="bg club", fullsize="bg club.jpg"),
]
